name: privacybot ci/cd
on: [push, repository_dispatch]
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Build and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf privacybot/
          git clone git@github.com:haha150/privacybot.git
#          docker stop privacybot:latest
#          docker system prune -a -f
#          cd privacybot/
#          docker build . -t privacybot:latest
#          docker run -d -e TOKEN=${{ secrets.TOKEN }} -e PAT=${{ secrets.PAT }} -e USERNAME_GITHUB=${{ secrets.USERNAME_GITHUB }} privacybot:latest
#          cd ..
          rm -rf privacybot/
